es:
    url: localhost
    port: 9300

spring:
    profiles:
        active: dev
euler:
    problem:
        url: "https://projecteuler.net/problem="
        css:
            body: "div.problem_content"

---
spring:
    profiles: dev

es:
    index: euler
    type: problem

---
spring:
    profiles: test

es:
    index: euler-test
    type: problem